security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            switch_user:
                parameter: _switch_user
                role: ROLE_ADMIN
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true
            logout:
                path: logout

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/initAppli, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: [ ROLE_USER, ROLE_ADMIN ] }    # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

